# Auto-generated by mtbmcp. Do not edit manually.
import json as _json

SESSION_INFO = _json.loads(r'''{
  "extension_dir": "c:/Users/Andi/.vscode/extensions/infineonag.modustoolbox-ai-0.2.1-win32-x64",
  "workspace_path": "c:/Projects/RAK_GAN_RSS_GITHUB/RAK_GAN_MOTOR_DEMO",
  "projects": [
    "RAK_GAN_MOTOR_DEMO"
  ],
  "device_name": "PSC3M5FDS2AFQ1",
  "bsp_name": "RAK_GAN_rev1",
  "board_target": "TARGET_RAK_GAN_rev1",
  "cy_tools_path": "C:/Users/Andi/ModusToolbox/tools_3.8",
  "modus_shell_path": "C:/Users/Andi/ModusToolbox/tools_3.8/modus-shell",
  "tcp_port": 60909,
  "ext_port": 60908,
  "pid": 14472,
  "log_level": "info",
  "log_file": "C:/Users/Andi/AppData/Local/Temp/mtbai-logs/mtbai.log"
}''')

for _key, _value in SESSION_INFO.items():
    globals()[_key.upper()] = _value

del _json
del _key
del _value
